seed: 1337

data:
  rdd_root: /share_data/data
  train_split: train
  val_split: val
  split_mode: random
  train_ratio: 0.8
  val_ratio: 0.1
  xml_glob: "**/annotations/xmls/*.xml"
  image_dir_hint: "images"
  countries: null
  allowed_labels: [D00, D10, D20, D40]
  hflip_prob: 0.5

model:
  name: fasterrcnn_resnet50_fpn
  pretrained: true
  freeze_backbone: true

train:
  multiscale_min_sizes: [480, 512, 544, 576, 608, 640]
  multiscale_max_size: 1333
  epochs: 50
  batch_size: 2
  grad_accum_steps: 8
  num_workers: 6
  optimizer: sgd
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  grad_clip: 5.0
  scheduler: cosine
  early_stopping_patience: 10

outputs:
  root_dir: outputs/fasterrcnn_frozen
  checkpoints_dir: outputs/fasterrcnn_frozen/checkpoints
  logs_dir: outputs/fasterrcnn_frozen/logs
  best_checkpoint_name: best.pt
  history_name: history.json
