seed: 1337

data:
  split_dir: data/crops_80.10.10_split
  image_size: 224
  countries: null
  allowed_labels: [D00, D10, D20, D40]
  cache_images: true

model:
  name: vit_tiny_patch16_224
  pretrained: true
  freeze_backbone: false

train:
  epochs: 20
  batch_size: 128 # 32 was the previous
  num_workers: 12 # 4 was the previous
  prefetch_factor: 4
  optimizer: adamw
  lr: 0.00005
  weight_decay: 0.0001
  scheduler: cosine
  early_stopping_patience: 5
  min_delta: 0.001

outputs:
  root_dir: outputs/vit_finetune
  checkpoints_dir: outputs/vit_finetune/checkpoints
  logs_dir: outputs/vit_finetune/logs
  figures_dir: outputs/vit_finetune/figures
  label_map_path: outputs/vit_finetune/label_map.json
  best_checkpoint_name: best.pt
  history_name: history.json